use anyhow::{bail, Result};
use std::path::Path;

// TODO(#4): once the `admin-token generate` subcommand lands (Wave 3),
// move the token-minting logic into a shared helper and call it from here.
fn generate_admin_token() -> String {
    crate::crypto::random_hex::<32>()
}

const CONFIG_TEMPLATE: &str = r#"[server]
bind = "127.0.0.1:3000"
ingest_bind = "0.0.0.0:3001"
# external_url        = "https://stackpit.example.com"          # public admin/UI URL
# external_ingest_url = "https://ingest.stackpit.example.com"   # only if ingest lives on a different host:port
#                                                               # (defaults to external_url, then http://{ingest_bind})
# Generated by `stackpit init`. Required for the admin UI unless [auth.oauth]
# is configured, or you accept the no-auth posture on loopback via
# `no_auth_loopback_acknowledged = true`. Rotate with `openssl rand -hex 32`.
admin_token = "__ADMIN_TOKEN__"
# force_secure_cookies = true   # set when behind a TLS-terminating proxy (nginx/Caddy) and external_url is https
# no_auth_loopback_acknowledged = true   # only valid on loopback binds; lets you run with no auth at all

[storage]
path = "stackpit.db"
retention_days = 90

[filter]
mode = "open"

# OAuth / SSO via Hydra. Leave [auth.oauth] out to run admin_token-only.
# Requires STACKPIT_MASTER_KEY (64 hex chars) -- tokens are stored
# encrypted at rest in the oidc_grants table.
# See the README's Authentication section for the full Hydra client setup.
#
# [auth.oauth]
# issuer_url                  = "https://hydra.example.com"
# client_id                   = "stackpit"
# client_secret               = "..."
# redirect_uri                = "https://stackpit.example.com/web/auth/callback"
# post_logout_redirect_uri    = "https://stackpit.example.com/web/login"
# # Must share the origin of server.external_url. Set
# # post_logout_allow_cross_origin = true to land users on a different
# # origin after logout (e.g. a marketing site).
# # post_logout_allow_cross_origin = false
# required                    = false   # true = fail startup if OIDC discovery fails
# # allow_local_only_logout    = false   # set true if your IdP omits end_session_endpoint
#                                       # (logout signs out of Stackpit only, not the IdP).
#                                       # Otherwise: required=true refuses to start; required=false
#                                       # warns on every boot.
# # web_audience              = "stackpit-web"  # audience the web BFF expects on access tokens;
#                                       # bind this to the IdP audience for the web client to
#                                       # block confused-deputy attacks across resource servers.
# # access_token_max_ttl_secs = 86400   # ceiling for back-channel revocation TTL
# # refresh_token_max_ttl_secs = 1209600  # 14d default; ceiling for marker TTL when
#                                       # a refresh token might outlast the access token.
#                                       # Should match Hydra's lifespans.refresh_token.
#                                       # Hard-capped at 90 days (7776000s) at startup.
# # introspection_cache_ttl_secs = 60   # positive cache for the web bearer gate
# # cache_max_ttl_secs         = 30     # hard ceiling on the web cache entry TTL;
#                                       # 0 disables the cache (range 0-300)
# # introspection_url          = "..."  # defaults to mcp.introspection_url
#
# MCP endpoint at POST /mcp. Requires [auth.oauth] above.
#
# Token validation order:
#   1. admin_token break-glass (server.admin_token if set; constant-time eq)
#   2. JWT access tokens — RS256 against the IdP's JWKS (recommended;
#      Hydra's default since the JWT-by-default flip)
#   3. Opaque tokens — RFC 7662 introspection (admin URL preferred;
#      discovery's `introspection_endpoint` as fallback)
#
# At least one of (JWKS reachable) or (introspection URL set) or
# (discovery exposes `introspection_endpoint`) is required at startup.
#
# [auth.mcp]
# audience            = "https://stackpit.example.com"
# # introspection_url = "https://hydra-admin.internal:4445/admin/oauth2/introspect"
# # jwks_url          = "..."           # override; defaults to discovery's jwks_uri
# # jwks_cache_ttl_secs = 86400         # 24h; refetch on kid miss regardless
# # cache_max_ttl_secs  = 30            # hard ceiling on positive bearer cache TTL;
#                                       # 0 disables the cache (range 0-300)
"#;

pub fn run(path: &Path) -> Result<()> {
    if path.exists() {
        bail!("{} already exists", path.display());
    }

    let token = generate_admin_token();
    let contents = CONFIG_TEMPLATE.replace("__ADMIN_TOKEN__", &token);

    std::fs::write(path, contents)?;
    println!("created {}", path.display());
    println!("admin token generated and written to config (64 hex chars)");
    Ok(())
}
