//! Commercial-tier license gate.
//!
//! The MIT core (everything outside this module) ships without any of the
//! capabilities listed in `MONETIZATION.md`. This module itself is governed by
//! `LICENSE-COMMERCIAL` at the repo root (Stackpit Commercial License 1.0, SPDX
//! `LicenseRef-Stackpit-Commercial-1.0`) — source-available, free for
//! development / evaluation / personal hobbyist use, requires a valid
//! Ed25519-signed Commercial License Key for production use, and forbids
//! operating Stackpit as a hosted service for third parties without a separate
//! agreement.
//!
//! Design:
//!
//! 1. **Offline-signed.** Licenses are Ed25519-signed CBOR blobs (see the
//!    `license-issuer` repo). Stackpit verifies against [`PUBLIC_KEY_BYTES`] —
//!    baked in at build time — and never phones home.
//!
//! 2. **Single-license model.** One signed blob per Stackpit install,
//!    persisted in the `stackpit_license` row (singleton PK). Activated via
//!    `/web/admin/license`; deactivation is a row DELETE.
//!
//! 3. **Lock-free reads.** The verified status sits behind an
//!    [`arc_swap::ArcSwap`] so every check is a single atomic pointer load.
//!
//! 4. **Grace period.** Expired licenses keep gated features visible but
//!    read-only for a fixed 30-day window ([`GRACE_DAYS`]) so a forgotten
//!    renewal doesn't blow up production.
//!
//! Two features are gated today: observability (the Prometheus `/metrics`
//! endpoint) and integrations (Slack, webhooks, and the issue trackers, whose
//! implementations live in [`providers`]). Adding another is a new
//! [`license::Feature`] variant plus its call-site gate.

pub mod license;
pub mod providers;
pub mod settings_page;
pub mod store;
pub mod verify;

use license::Feature;
pub use license::{FeatureStatus, LicenseStatus, GRACE_DAYS};

use std::sync::Arc;

use arc_swap::ArcSwap;

/// Ed25519 public key Stackpit verifies licenses against. Generated by the
/// `license-issuer` and committed to the repo so reproducible builds emit
/// identical binaries. To rotate, re-key the issuer, replace this file, and
/// re-issue every outstanding license (every prior license becomes invalid
/// after rotation — there's no overlap window).
pub const PUBLIC_KEY_BYTES: &[u8; 32] = include_bytes!("pubkey.bin");

/// Second accepted key: the licence shop's *web* signing key. The shop at
/// licenses.gofranz.com is internet-facing and signs with this one, while
/// [`PUBLIC_KEY_BYTES`]'s private half stays offline for hand-issued licences.
/// Both are accepted, so if the shop host is ever compromised the web key can
/// be rotated and only web-sold licences need re-issuing — root-signed ones
/// keep working. Rotating this one is cheap; rotating the root one is not.
pub const WEB_PUBLIC_KEY_BYTES: &[u8; 32] = include_bytes!("web-pubkey.bin");

/// Runtime handle. Wraps an [`ArcSwap`] so swaps (activate / deactivate) are
/// atomic and reads are wait-free. Cheap to clone; lives on
/// [`crate::server::AppState`].
#[derive(Clone)]
pub struct LicenseHandle {
    inner: Arc<ArcSwap<LicenseStatus>>,
    /// Grace window applied to expired licenses, in days. Fixed at
    /// [`GRACE_DAYS`]; cached here so feature checks stay self-contained.
    grace_days: i64,
}

impl LicenseHandle {
    pub fn new(initial: LicenseStatus, grace_days: i64) -> Self {
        Self {
            inner: Arc::new(ArcSwap::from_pointee(initial)),
            grace_days,
        }
    }

    /// Snapshot the current status. The returned `Arc` doesn't reflect later
    /// swaps; callers that need a long-lived reference should re-read rather
    /// than caching across awaits.
    pub fn status(&self) -> Arc<LicenseStatus> {
        self.inner.load_full()
    }

    /// Swap in a new status. Called by the activate handler and at boot.
    pub fn swap(&self, next: LicenseStatus) {
        self.inner.store(Arc::new(next));
    }

    pub fn grace_days(&self) -> i64 {
        self.grace_days
    }

    /// Feature gate. Returns [`FeatureStatus::Allowed`] when the license
    /// covers `feature` and isn't past its hard-gate date,
    /// [`FeatureStatus::GraceReadOnly`] inside the grace window,
    /// [`FeatureStatus::Locked`] otherwise.
    pub fn feature(&self, feature: Feature) -> FeatureStatus {
        let status = self.status();
        license::evaluate_feature(&status, feature)
    }

    /// Re-classify against `now`, swapping only on a variant change. Returns
    /// the new label on transition, else `None`.
    pub fn reclassify(&self, now: chrono::DateTime<chrono::Utc>) -> Option<&'static str> {
        let current = self.status();
        let license = current.license()?;
        let next = license::classify(license.clone(), self.grace_days, now);
        if license::status_variant(&next) == license::status_variant(&current) {
            return None;
        }
        let label = license::status_variant(&next);
        self.swap(next);
        Some(label)
    }
}

/// A handle licensed for every [`Feature`], for tests whose subject isn't the
/// license itself. Gate behaviour is tested directly in [`providers`].
#[cfg(test)]
pub fn fully_licensed() -> LicenseHandle {
    use license::License;
    LicenseHandle::new(
        LicenseStatus::Active(License {
            license_id: "test".into(),
            customer: "Test Co".into(),
            email: "t@example.com".into(),
            issued_at: chrono::Utc::now(),
            expires_at: Some(chrono::Utc::now() + chrono::Duration::days(365)),
            features: vec![Feature::Observability, Feature::Integrations],
            max_orgs: None,
        }),
        GRACE_DAYS,
    )
}

use tokio_util::sync::CancellationToken;

/// Hourly tick that re-runs the expiry math so a license that booted `Active`
/// crosses into grace/expired between restarts.
pub fn spawn_reclassify(license: LicenseHandle, cancel: CancellationToken) {
    crate::background::supervise("license_reclassify", async move {
        use std::time::Duration;
        loop {
            tokio::select! {
                _ = cancel.cancelled() => return,
                _ = tokio::time::sleep(Duration::from_secs(3600)) => {}
            }
            if let Some(label) = license.reclassify(chrono::Utc::now()) {
                tracing::warn!(
                    status = label,
                    "license: status transitioned on periodic re-classification"
                );
            }
        }
    });
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::commercial::license::{License, LicenseStatus};
    use chrono::{Duration, Utc};

    fn active_handle(expires_in_days: i64) -> LicenseHandle {
        let license = License {
            license_id: "test".into(),
            customer: "Test Co".into(),
            email: "t@example.com".into(),
            issued_at: Utc::now(),
            expires_at: Some(Utc::now() + Duration::days(expires_in_days)),
            features: Vec::new(),
            max_orgs: None,
        };
        LicenseHandle::new(LicenseStatus::Active(license), GRACE_DAYS)
    }

    #[test]
    fn reclassify_moves_active_into_grace_then_expired() {
        let handle = active_handle(10);
        let into_grace = Utc::now() + Duration::days(11);
        assert_eq!(handle.reclassify(into_grace), Some("Grace"));
        let past_grace = Utc::now() + Duration::days(10 + GRACE_DAYS + 5);
        assert_eq!(handle.reclassify(past_grace), Some("Expired"));
    }

    #[test]
    fn reclassify_noop_while_still_active() {
        let handle = active_handle(30);
        assert_eq!(handle.reclassify(Utc::now() + Duration::days(1)), None);
    }
}
